# Generated by Django 3.0.2 on 2020-01-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200127_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_date',
            new_name='pub_date',
        ),
    ]
